[workspace]
# List the paths to the packages included in this workspace
members = [
    "exercise_collatz_sequence",
]

# You can define shared settings here (Rust 2024 edition)
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["ACFHarbinger"]